### ISSUE TITLE
add Taiwan

### ISSUE THREAD

**Issue by Zhuyuan0907** [TenkyuChimata/MCEEW#1]
can this plugins add Taiwan?
I'm live in Taiwan, and I wanna let me server to use this plugin :)

**Comment by TenkyuChimata** [comment]
i will consider this in the future as i currently don't have CWB EEW source.

**Comment by Zhuyuan0907** [comment]
> i will consider this in the future as i currently don't have CWB EEW source.

Hope you can get it!

**Comment by block10145** [comment]
> i will consider this in the future as i currently don't have CWB EEW source.

I have a build similar thing, don't know if it can help
https://github.com/ExpTechTW/TW-EEW

**Comment by TenkyuChimata** [comment]
v2.2.1已更新支援台灣CWB EEW
詳見https://www.spigotmc.org/resources/mceew-earthquake-early-warning.104549/updates
