### ISSUE TITLE
web socket error

### ISSUE THREAD

**Issue by RiverTeacher** [TenkyuChimata/MCEEW#10]
![image](https://github.com/TenkyuChimata/MCEEW/assets/75714738/9c0c7065-2c1d-4b80-aa61-cae188af92e1)
Communication fails with an error like the one in the console.

**Comment by TenkyuChimata** [comment]
If it occurs infrequently, which is usually normal.

**Comment by RiverTeacher** [comment]
![image](https://github.com/TenkyuChimata/MCEEW/assets/75714738/fc3c4ceb-c135-44e2-b44a-e9b5b396d4bb)
It occurs all the time.

**Comment by TenkyuChimata** [comment]
It looks as if your server can't access the external network, are you using a panel or a vps?

**Comment by RiverTeacher** [comment]
I`m using panel

**Comment by TenkyuChimata** [comment]
Please contact the panel provider, it looks like they don't allow MCEEW to connect to the Internet.

**Comment by RiverTeacher** [comment]
okay.thanks for your help!
